# Generated by Django 5.2 on 2025-05-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
